[theme]
base="dark"
primaryColor="00a8e5"
[client]
toolbarMode = "minimal"

[[pages]]
path = "ğŸ‘‹_Welcome.py"
name = "Welcome"
icon = "ğŸ‘‹"

[[pages]]
name = "Players"
icon = "ğŸ§”ğŸ»â€â™‚ï¸Players"
is_section = true

# Pages after an `is_section = true` will be indented
[[pages]]
name = "1_ğŸ§”ğŸ»â€â™‚ï¸Player_Stats.py"
icon = "ğŸ§”ğŸ»â€â™‚ï¸"

# Unless you explicitly say in_section = false`
[[pages]]
name = "Teams"
icon = "ğŸ§”ğŸ»â€â™‚ï¸Teams"
in_section = true

[[pages]]
name = "2_ğŸ‘•_Team_Stats.py"
icon = "ğŸ‘•"
